on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
    types: [opened, synchronize]
  workflow_dispatch:

name: Terraform pipeline

permissions:
  contents: read  # Only read access to repo contents
  id-token: write # Grant write permission only if OIDC is used

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    permissions:
      contents: read  # Only read access to repository contents
      actions: read   # Only read access to GitHub Actions
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./ 
          quiet: false
          soft_fail: false
          framework: terraform
          output_format: cli
          download_external_modules: true
          log_level: DEBUG
